server:
  port: 8086

spring:
  application:
    name: library-analytics
  datasource:
    url: jdbc:postgresql://localhost:5432/library_analytics
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
      acks: all
      retries: 3
    consumer:
      group-id: library-analytics
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer 使用 StringDeserializer：Consumer 手动解析 JSON（防腐层设计）
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
    topic:
      domain-events: library.analytics.events

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
