server:
  port: 8087

spring:
  application:
    name: library-notification
  datasource:
    url: jdbc:postgresql://localhost:5432/library_notification
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    # notification 是纯消费方，无 producer 配置
    bootstrap-servers: localhost:29092
    consumer:
      group-id: library-notification
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # value-deserializer 使用 StringDeserializer：Consumer 手动解析 JSON（防腐层设计）
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
